### ISSUE TITLE
Add Entities cleanup per safezone

### ISSUE THREAD

**Issue by TheDmitri** [TheDmitri/TraderPlusSafeZone#2]
This feature must add the ability for server owner to activate a entity cleanup per safezone and define the entities that won't be kill. (such as DayZ Dogs or Horses).

**Comment by Sitrixs** [comment]
Re-Adjusted the code.
1. Removed the not needed RPC.
2. Client only sends information regarding the safezones themselves.
3. RPC that is sent to the server prompts the server to check the safezones and perform the clean up.
4. Tests in game, show desired result of Zombies and animals being cleaned up from the zone.
5. Toggle of Clean up seem to work as intended in individual zones.
6. Toggle of Clean up  seem to work as intended with the exclusion array.
